"""
Navigate to an ArUco marker using ``PilotToArucoMarker`` / ``PilotToPose`` (RRT).

Book markers (ArUco id >= ``BOOK_FIRST_ID``) and 3D book view live in ``aim_librarian``;
``vex-aim-tools`` stays unmodified.

Requires ``vex-aim-tools`` and this repo on ``PYTHONPATH``. Edit ``NavigateToMarker.fsm`` and regenerate with::

    python3 path/to/vex-aim-tools/genfsm NavigateToMarker.fsm NavigateToMarker.py
"""

from aim_fsm import *

from aim_librarian import install_librarian_extensions
from aim_librarian.pilot_ext import PilotToArucoMarker


class NavigateToMarker(StateMachineProgram):

    def __init__(self, marker_id=9, **kwargs):
        self.marker_id = marker_id
        opts = dict(
            speech=False,
            launch_path_viewer=True,
        )
        opts.update(kwargs)
        super().__init__(**opts)
        install_librarian_extensions(self.robot)

    class NavDonePrint(StateNode):
        def start(self, event=None):
            super().start(event)
            print(
                'NavigateToMarker: completed run toward marker',
                self.parent.marker_id,
            )
            self.post_completion()

    class NavFailPrint(StateNode):
        def start(self, event=None):
            super().start(event)
            print(
                'NavigateToMarker: failed for marker',
                self.parent.marker_id,
            )
            self.post_completion()

    def setup(self):
        #         travel: PilotToArucoMarker(self.marker_id)
        #         travel =C=> ok
        #         travel =F=> bad
        # 
        #         ok: self.NavDonePrint() =N=> done
        # 
        #         bad: self.NavFailPrint() =N=> done
        # 
        #         done: ParentCompletes()
        
        # Code generated by genfsm on Fri Apr  3 16:04:51 2026:
        
        travel = PilotToArucoMarker(self.marker_id) .set_name("travel") .set_parent(self)
        ok = self.NavDonePrint() .set_name("ok") .set_parent(self)
        bad = self.NavFailPrint() .set_name("bad") .set_parent(self)
        done = ParentCompletes() .set_name("done") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(travel) .add_destinations(ok)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(travel) .add_destinations(bad)
        
        nulltrans1 = NullTrans() .set_name("nulltrans1")
        nulltrans1 .add_sources(ok) .add_destinations(done)
        
        nulltrans2 = NullTrans() .set_name("nulltrans2")
        nulltrans2 .add_sources(bad) .add_destinations(done)
        
        return self
